# This file configures the analyzer to use the lint rule set from `package:lint`

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
# include: package:flutter_lints/flutter.yaml

include: package:lint/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # Choose wisely, but you don't have to
    # prefer_double_quotes: true
    prefer_single_quotes: true

    sort_pub_dependencies: false

    avoid_dynamic_calls: false