name: iot_agriculture
description: IOT Agriculture Techno Space
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Style And Widgets
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  easy_localization: ^3.0.1

  # FIREBASE
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_database: ^10.0.6
  firebase_messaging: ^14.1.1
  firebase_storage: ^11.0.6
  flutter_facebook_auth: ^3.5.0

  # App Helper
  flutter_bloc: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  flutter_svg_provider: ^1.0.3
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  firebase_core_platform_interface: ^4.5.2
  flutter_animated_button: ^2.0.2
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0
  flutter_switch: ^0.3.2
  dots_indicator: ^2.1.0
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  # App Analyzer
  lint: ^1.10.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  # APP ASSETS
  assets:
    - assets/svg/
    - assets/images/
    - assets/translations/

  # APP Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Fonts/Montserrat-Black.ttf
        - asset: assets/Fonts/Montserrat-Bold.ttf
        - asset: assets/Fonts/Montserrat-Regular.ttf
