// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTRXWD2Rbx9mZnjQDa-s0A5GsOrL-Ia5c',
    appId: '1:865205848684:web:321f34bb7ab421cd816649',
    messagingSenderId: '865205848684',
    projectId: 'iot-agriculture-faedb',
    authDomain: 'iot-agriculture-faedb.firebaseapp.com',
    storageBucket: 'iot-agriculture-faedb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHofMXLIzkDJ1_6IJ5Gzdlhn2qlykI1w',
    appId: '1:865205848684:android:eeb59e13e530eb8a816649',
    messagingSenderId: '865205848684',
    projectId: 'iot-agriculture-faedb',
    storageBucket: 'iot-agriculture-faedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6RiwGbmrUFCPjSOZRgi1uP6dBkmAVSc0',
    appId: '1:865205848684:ios:b19618edc9c0e82f816649',
    messagingSenderId: '865205848684',
    projectId: 'iot-agriculture-faedb',
    storageBucket: 'iot-agriculture-faedb.appspot.com',
    iosClientId: '865205848684-9mn54fnc1tbn9gbj2dkkt0ufadkgmbsl.apps.googleusercontent.com',
    iosBundleId: 'com.technospace.iotAgriculture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6RiwGbmrUFCPjSOZRgi1uP6dBkmAVSc0',
    appId: '1:865205848684:ios:b19618edc9c0e82f816649',
    messagingSenderId: '865205848684',
    projectId: 'iot-agriculture-faedb',
    storageBucket: 'iot-agriculture-faedb.appspot.com',
    iosClientId: '865205848684-9mn54fnc1tbn9gbj2dkkt0ufadkgmbsl.apps.googleusercontent.com',
    iosBundleId: 'com.technospace.iotAgriculture',
  );
}
